### ISSUE TITLE
Invalid type hints for explicit Optional fields

### ISSUE THREAD

**Issue by camilovelezr** [koxudaxi/datamodel-code-generator#1203]
In a schema where a field is not required *and* its value is `anyOf`: {...} where `type: ["null"]` is one of `anyOf`, an invalid type hint that looks like `myfield: Optional[Union[str, Optional[]]]` is generated.

**To Reproduce**

Example schema:
```json
{
  "type": "object",
  "additionalProperties": false,
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "id1",
  "title": "Validating Schema ID1",
  "properties": {
    "in": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "input_dataset_path": {
          "type": "string",
          "minLength": 1,
          "title": "Path to the input dataset",
          "description": "d1"
        },
        "config": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "title": "t2",
              "description": "d2"
            },
            {
              "type": [
                "null"
              ],
              "title": "t3",
              "description": "d3"
            }
          ]
        }
      }
    },
    "n1": {
      "type": "integer"
    }
  }
}

```

Used commandline:
```
$ datamodel-codegen --input test.json --output test_schema.py --field-constraints
```

**Expected behavior**
Type hint for `config` should be `Optional[ConfigItem]`.

**Current behavior**
```
 $ datamodel-codegen --input test.json --output test_schema.py -
-field-constraints
Traceback (most recent call last):
  File "/Users/<>/miniforge3/lib/python3.9/site-packages/datamodel_code_generator/__main__.py", line 592, in main
    generate(
  File "/Users/<>/miniforge3/lib/python3.9/site-packages/datamodel_code_generator/__init__.py", line 375, in generate
    results = parser.parse()
  File "/Users/<>/miniforge3/lib/python3.9/site-packages/datamodel_code_generator/parser/base.py", line 747, in parse
    body = code_formatter.format_code(body)
  File "/Users/<>/miniforge3/lib/python3.9/site-packages/datamodel_code_generator/format.py", line 127, in format_code
    code = self.apply_black(code)
  File "/Users/<>/miniforge3/lib/python3.9/site-packages/datamodel_code_generator/format.py", line 131, in apply_black
    return black.format_str(
  File "src/black/__init__.py", line 1131, in format_str
  File "src/black/__init__.py", line 1141, in _format_str_once
  File "src/black/parsing.py", line 128, in lib2to3_parse
black.parsing.InvalidInput: Cannot parse: 16:48:     config: Optional[Union[ConfigItem, Optional[]]] = None
```

**Version:**
 - OS: macOS Ventura 13.2.1 - M1 Pro
 - Python version: 3.9.10
 - datamodel-code-generator version: 0.14.0

**Additional context**
I have a proposed fix that I can put in a PR.

**Comment by camilovelezr** [comment]
@koxudaxi Thank you very much!!
