### ISSUE TITLE
Parsing jsonschema breaks if the attribute 'self' exists in root schema

### ISSUE THREAD

**Issue by rezen** [koxudaxi/datamodel-code-generator#1317]
**Describe the bug**
I noticed with a particular jsonschema the parsing breaks if the attribute `self` exists.

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/datamodel_code_generator/__main__.py", line 689, in main
    generate(
  File "/opt/homebrew/lib/python3.11/site-packages/datamodel_code_generator/__init__.py", line 464, in generate
    results = parser.parse()
              ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/datamodel_code_generator/parser/base.py", line 961, in parse
    self.parse_raw()
  File "/opt/homebrew/lib/python3.11/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1567, in parse_raw
    self._parse_file(self.raw_obj, obj_name, path_parts)
  File "/opt/homebrew/lib/python3.11/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1627, in _parse_file
    root_obj = JsonSchemaObject.parse_obj(raw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
TypeError: JsonSchemaObject.__init__() got multiple values for argument 'self'
```
**To Reproduce**

Download the json schema found here https://gitlab.com/gitlab-org/security-products/security-report-schemas/-/blob/master/dist/container-scanning-report-format.json

Used commandline:
```
$  datamodel-codegen --input-file-type  jsonschema --input ~/Downloads/container-scanning-report-format.json --output $PWD/model.py
```

**Version:**
 - OS: MacOS Monterey - 12.6.4
 - Python version: 3.11.3
 - datamodel-code-generator version: 0.19.0

**Comment by rezen** [comment]
PR to fix https://github.com/koxudaxi/datamodel-code-generator/pull/1318
