### ISSUE TITLE
numerical field with an exponent in the minimum does not work

### ISSUE THREAD

**Issue by j-carson** [koxudaxi/datamodel-code-generator#1378]
**Describe the bug**
A jsonschema with an exponent in the "minimum" field generates a model on version 0.18.0 but throws an error on version 0.20.0

**To Reproduce**

Example schema:
```json
{"additionalProperties": true, "properties": {"field_here": {"description": "minimum has an exponent maybe that explains it", "type": "number", "maximum": 1, "minimum": 1e-08, "cpp_type": "float"}}, "required": [], "title": "test_case", "type": "object", "description": "smaller test case"}
```

Used commandline:
```
$ datamodel-codegen --input test_case.json --output test_case.py
The input file type was determined to be: jsonschema
This can be specificied explicitly with the `--input-file-type` option.
Traceback (most recent call last):
  File "/home/pathstuff/.nox/codegen/lib/python3.10/site-packages/datamodel_code_generator/__main__.py", line 709, in main
    generate(
  File "/home/pathstuff/.nox/codegen/lib/python3.10/site-packages/datamodel_code_generator/__init__.py", line 468, in generate
    results = parser.parse()
  File "/home/pathstuff/.nox/codegen/lib/python3.10/site-packages/datamodel_code_generator/parser/base.py", line 956, in parse
    self.parse_raw()
  File "/home/pathstuff/.nox/codegen/lib/python3.10/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1568, in parse_raw
    self._parse_file(self.raw_obj, obj_name, path_parts)
  File "/home/pathstuff/.nox/codegen/lib/python3.10/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1630, in _parse_file
    root_obj = JsonSchemaObject.parse_obj(raw)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "/home/pathstuff/.nox/codegen/lib/python3.10/site-packages/datamodel_code_generator/parser/jsonschema.py", line 241, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for JsonSchemaObject
properties -> field_here -> minimum
  1e-08 is not int or float (type=type_error)
properties -> field_here
  value could not be parsed to a boolean (type=type_error.bool)
```

**Expected behavior**
I got this output with 0.18.0 with no error: 

```python
# generated by datamodel-codegen:
#   filename:  test_case.json
#   timestamp: 2023-06-22T00:23:05+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Extra, Field, confloat


class TestCase(BaseModel):
    class Config:
        extra = Extra.allow

    field_here: Optional[confloat(ge=1e-08, le=1.0)] = Field(
        None, description='minimum has an exponent maybe that explains it'
    )
```

**Version:**
 - OS: Ubuntu 20.04
 - Python version: 3.10
 - datamodel-code-generator version: 0.20.0

**Comment by santhoshramaraj** [comment]
Faced the same error with maximum field as 1E+3 int

To work around, I had to fix the schema manually.

Version
- datamodel-code-generator version : 0.22.0
- Python : 3.8.10

**Comment by koxudaxi** [comment]
@j-carson  @santhoshramaraj 
The fixed version was released
Thank you very much!!
