### ISSUE TITLE
OpenAPI components/schemas/$ref doesn't appear to load/parse local file

### ISSUE THREAD

**Issue by indrat** [koxudaxi/datamodel-code-generator#1382]
**Describe the bug**
Given an openapi yaml file with a components schemas element where the content is a `$ref` to another schema document the value of `$ref` doesn't appear to be loaded/parsed and the raw string is passed to `JsonSchemaObject.parse_obj` which fails as it is not a dict.

The openapi spec at [4.8.23.3](https://spec.openapis.org/oas/v3.1.0#relative-schema-document-example) seems to indicate that a `$ref` to a complete document is valid.

```
› datamodel-codegen --input src/openapi.yaml --output build/
Traceback (most recent call last):
  File "pydantic/main.py", line 522, in pydantic.main.BaseModel.parse_obj
ValueError: dictionary update sequence element #0 has length 1; 2 is required

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "data-model-code-gen/venv/lib/python3.10/site-packages/datamodel_code_generator/__main__.py", line 709, in main
    generate(
  File "data-model-code-gen/venv/lib/python3.10/site-packages/datamodel_code_generator/__init__.py", line 468, in generate
    results = parser.parse()
  File "data-model-code-gen/venv/lib/python3.10/site-packages/datamodel_code_generator/parser/base.py", line 956, in parse
    self.parse_raw()
  File "data-model-code-gen/venv/lib/python3.10/site-packages/datamodel_code_generator/parser/openapi.py", line 544, in parse_raw
    self.parse_raw_obj(
  File "data-model-code-gen/venv/lib/python3.10/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1503, in parse_raw_obj
    self.parse_obj(name, JsonSchemaObject.parse_obj(raw), path)
  File "pydantic/main.py", line 525, in pydantic.main.BaseModel.parse_obj
pydantic.error_wrappers.ValidationError: 1 validation error for JsonSchemaObject
__root__
  JsonSchemaObject expected dict not str (type=type_error)
```

**To Reproduce**
Example repo that uses `$ref`s to schema documents - https://github.com/dgarcia360/openapi-boilerplate

```
git clone https://github.com/dgarcia360/openapi-boilerplate.git
cd openapi-boilerplate
datamodel-codegen --input src/openapi.yaml --output build/
```

Example schema `openapi.yaml`:
```yaml

openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  description: Multi-file boilerplate for OpenAPI Specification.
  license:
    name: MIT
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
servers:
  - url: http://petstore.swagger.io/v1
tags:
  - name: pets
paths:
  /pets:
    $ref: "./resources/pets.yaml"
  /pets/{petId}:
    $ref: "./resources/pet.yaml"
components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"

```
`schemas/_index.yaml`:
```yaml
Pet:
  $ref: "./Pet.yaml"
```

`schemas/Pet.yaml`:
```yaml
type: object
required:
  - id
  - name
properties:
  id:
    type: integer
    format: int64
  name:
    type: string
  tag:
    type: string
```

Used commandline:
```
$ datamodel-codegen --input src/openapi.yaml --output build
```

**Expected behavior**
The local relative schema files are loaded, parsed and a pydantic model is generated successfully.

**Version:**
 - OS: macOS 12.6
 - Python version: Python 3.10.8
 - datamodel-code-generator version: 0.20.0

**Comment by indrat** [comment]
Actually reading https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#components-object a little closer it appears that that example schema is probably invalid as the various elements of the `components` object are defined as being `Map[string, * Object]` (or `Map[string, * Object | Reference Object]` in the older 3.0.0 spec), rather than as `Map[string, * Object] | Reference Object` so it appears that a `$ref` *can't* be used directly under `components/schemas`.

Closing as the example schema was probably invalid.
