### ISSUE TITLE
AttributeError raised when using --collapse-root-models flag

### ISSUE THREAD

**Issue by howardj99** [koxudaxi/datamodel-code-generator#1419]
**Describe the bug**

When using the `--collapse-root-models` flag, this error is raised:

```shell
Traceback (most recent call last):
  File ".venv/lib/python3.10/site-packages/datamodel_code_generator/__main__.py", line 767, in main
    generate(
  File ".venv/lib/python3.10/site-packages/datamodel_code_generator/__init__.py", line 431, in generate
    results = parser.parse()
  File ".venv/lib/python3.10/site-packages/datamodel_code_generator/parser/base.py", line 1083, in parse
    self.__collapse_root_models(models, unused_models)
  File ".venv/lib/python3.10/site-packages/datamodel_code_generator/parser/base.py", line 856, in __collapse_root_models
    root_type_model.reference.children = [
  File ".venv/lib/python3.10/site-packages/datamodel_code_generator/parser/base.py", line 857, in <listcomp>
    c for c in root_type_model.reference.children if c.parent
AttributeError: 'BaseModel' object has no attribute 'parent'
```

**To Reproduce**

Input schema: https://github.com/CycloneDX/specification/blob/1.5/schema/bom-1.5.schema.json

pyproject.toml config:

```toml
[tool.datamodel-codegen]
base-class = ".base.BaseModel"
collapse-root-models = true
disable-warnings = true
enum-field-as-literal = "one"
field-include-all-keys = true
input-file-type = "jsonschema"
reuse-model = true
set-default-enum-member = true
snake-case-field = true
target-python-version = "3.7"
use-annotated = true
use-default-kwarg = true
use-double-quotes = true
use-schema-description = true
use-standard-collections = true
use-subclass-enum = true
use-title-as-name = true
wrap-string-literal = true
```

Base class code:

```python
from pydantic import BaseModel as _BaseModel
from pydantic import Extra


class BaseModel(_BaseModel):
    class Config:
        allow_population_by_field_name = True
        arbitrary_types_allowed = True
        extra = Extra.allow
        use_enum_values = True

    def __hash__(self) -> int:
        return hash(repr(self))
```

**Expected behavior**

Collapse root models without raising an exception

**Version:**
 - OS: MacOS 13.4.1
 - Python version: 3.10
 - datamodel-code-generator version: 0.21.1

**Comment by howardj99** [comment]
Seems to work (at least for my use case, don't know if breaks others) if that line is changed to

```python
c for c in root_type_model.reference.children if getattr(c, "parent", None)
```

**Comment by imankulov** [comment]
@howardj99, I ran into the same problem as you and submitted a pull request with your fix and some tests to cover this scenario.

I'm not sure if it's a perfect solution or just a quick workaround. Only @koxudaxi can decide 😄
