### ISSUE TITLE
Error 'list' object has no attribute 'get' while generating for sarif json schema

### ISSUE THREAD

**Issue by JoranHonig** [koxudaxi/datamodel-code-generator#1442]
**Describe the bug**
I'm getting an attribute error while trying to generate a datamodel for the sarif standard.

**To Reproduce**

Used commandline:
```
$ docker run koxudaxi/datamodel-code-generator --url https://raw.githubusercontent.com/oasis-tcs/sarif-spec/main/Schemata/sarif-schema-2.1.0.json --output model.py 
```

**Expected behavior**
I expected it to generate the model.

I got this error:
```
The input file type was determined to be: jsonschema
This can be specificied explicitly with the `--input-file-type` option.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/datamodel_code_generator/__main__.py", line 767, in main
    generate(
  File "/usr/local/lib/python3.11/site-packages/datamodel_code_generator/__init__.py", line 433, in generate
    results = parser.parse()
              ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/datamodel_code_generator/parser/base.py", line 1011, in parse
    self.parse_raw()
  File "/usr/local/lib/python3.11/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1602, in parse_raw
    self._parse_file(self.raw_obj, obj_name, path_parts)
  File "/usr/local/lib/python3.11/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1671, in _parse_file
    obj = JsonSchemaObject.parse_obj(model)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/typing_extensions.py", line 2562, in wrapper
    return __arg(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 945, in parse_obj
    return cls.model_validate(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 480, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/datamodel_code_generator/parser/jsonschema.py", line 271, in __init__
    super().__init__(**data)
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
  File "/usr/local/lib/python3.11/site-packages/datamodel_code_generator/parser/jsonschema.py", line 195, in validate_exclusive_maximum_and_exclusive_minimum
    exclusive_maximum: Union[float, bool, None] = values.get('exclusiveMaximum')
                                                  ^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
```

**Version:**
 - datamodel-code-generator docker version: [0.21.2](https://hub.docker.com/layers/koxudaxi/datamodel-code-generator/0.21.2/images/sha256-39c5efed804b19d7896e728c6f306cc5d520efea00799b1b38b2e6fdffabc446?context=explore)

**Comment by JoranHonig** [comment]
this seems to be fixed now

**Comment by ChristineWmy** [comment]
Hi @JoranHonig, I am meeting the similar issues, could you share how did you solve it? thanks

**Comment by abstractalgo** [comment]
Had the same issue. Pydantic seems to be causing the issue, so we fixed it by pinning the dependency there to `pydantic<2` (this worked for us, but we didn't try higher versions because we didn't need to).
