### ISSUE TITLE
Fail to generate a class with `anyOf` definition in JSON schema

### ISSUE THREAD

**Issue by ca-simone-chiorazzo** [koxudaxi/datamodel-code-generator#1446]
**Describe the bug**

I'm unable to generate a class from a JSON schema that contains an `anyOf` definition, an unexpected error is raised.

**To Reproduce**

Example schema:
```json
{
  "$id": "Test",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "TestPayload",
  "type": "object",
  "title": "Test",
  "required": [
    "payload"
  ],
  "properties": {
    "payload": {
      "$ref": "#/$def/TestPayload"
    }
  },
  "$def": {
    "TestPayload": {
      "$id": "TestPayload",
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "description": "TestPayload",
      "type": "object",
      "title": "TestPayload",
      "required": [
        "rule"
      ],
      "properties": {
        "rule": {
          "type": "array",
          "description": "Rule",
          "items": {
            "anyOf": [
              {
                "type": "string",
                "enum": [
                  "AND",
                  "OR"
                ]
              },
              {
                "type": "object",
                "required": [
                  "attribute",
                  "operator",
                  "values"
                ],
                "properties": {
                  "attribute": {
                    "type": "string",
                    "description": "Attribute "
                  },
                  "operator": {
                    "type": "string",
                    "description": "Operator"
                  },
                  "values": {
                    "type": "array",
                    "description": "List of values",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}
```

Generated programmatically with:
```
generate(
                    tmp_input_path,
                    input_file_type=InputFileType.JsonSchema,
                    output=tmp_output_directory,
                    use_schema_description=True,
                    use_title_as_name=True,
                    strip_default_none=True,
                    extra_template_data=_get_extra_template_data(),
                )
```

**Expected behavior**
Be able to generate the class with an `anyOf` definition

**Version:**
 - Python version:
 - datamodel-code-generator version: [e.g. 22]

**Additional context**
Error received is:
```
/Users/user/Documents/Repositories/project/venv/lib/python3.8/site-packages/pydantic/main.py:292: UserWarning: Pydantic serializer warnings:
  Expected `Union[list[definition-ref], definition-ref, bool]` but got `JsonSchemaObject` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
/Users/user/Documents/Repositories/project/venv/lib/python3.8/site-packages/pydantic/main.py:292: UserWarning: Pydantic serializer warnings:
  Expected `Union[list[definition-ref], definition-ref, bool]` but got `JsonSchemaObject` - serialized value may not be as expected
  Expected `Union[definition-ref, bool]` but got `JsonSchemaObject` - serialized value may not be as expected
  Expected `Union[definition-ref, bool]` but got `JsonSchemaObject` - serialized value may not be as expected
  Expected `Union[definition-ref, bool]` but got `JsonSchemaObject` - serialized value may not be as expected
  Expected `Union[list[definition-ref], definition-ref, bool]` but got `JsonSchemaObject` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
Traceback (most recent call last):

  File "/Users/user/Documents/Repositories/project/src/cli.py", line 15, in <module>
    app_cli()

  File "/Users/user/Documents/Repositories/project/src/commands/json_to_pulsar_class_cli.py", line 12, in generate
    JsonToPulsarStrategy(

  File "/Users/user/Documents/Repositories/project/src/strategies/json_to_pulsar_strategy.py", line 44, in generate
    generate(

  File "/Users/user/Documents/Repositories/project/venv/lib/python3.8/site-packages/datamodel_code_generator/__init__.py", line 431, in generate
    results = parser.parse()

  File "/Users/user/Documents/Repositories/project/venv/lib/python3.8/site-packages/datamodel_code_generator/parser/base.py", line 1115, in parse
    body = code_formatter.format_code(body)

  File "/Users/user/Documents/Repositories/project/venv/lib/python3.8/site-packages/datamodel_code_generator/format.py", line 157, in format_code
    code = self.apply_black(code)

  File "/Users/user/Documents/Repositories/project/venv/lib/python3.8/site-packages/datamodel_code_generator/format.py", line 161, in apply_black
    return black.format_str(

  File "src/black/__init__.py", line 1085, in format_str

  File "src/black/__init__.py", line 1095, in _format_str_once

  File "src/black/parsing.py", line 100, in lib2to3_parse

black.parsing.InvalidInput: Cannot parse: 25:43: class RuleAttributePredicate(*):
```

**Comment by koxudaxi** [comment]
The issue is fixed in the latest version.
