### ISSUE TITLE
KeyError When Using 'allOf' with Relative Reference to Schema in Same Directory

### ISSUE THREAD

**Issue by pedrosmr** [koxudaxi/datamodel-code-generator#1549]
**Describe the bug**
When trying to import a property using `allOf` and referencing the property from a schema that's in a file in the same directory, the module raises a `KeyError` exception when trying to delete the reference due to its `base_path` having duplicate parts (notice the double `components/schema` in the key):

```
Traceback (most recent call last):
  File "datamodel_code_generator/__main__.py", line 768, in main
    generate(
  File "datamodel_code_generator/__init__.py", line 433, in generate
    results = parser.parse()
  File "datamodel_code_generator/parser/base.py", line 1056, in parse
    self.parse_raw()
  File "datamodel_code_generator/parser/openapi.py", line 555, in parse_raw
    self.parse_raw_obj(
  File "datamodel_code_generator/parser/jsonschema.py", line 1501, in parse_raw_obj
    self.parse_obj(name, JsonSchemaObject.parse_obj(raw), path)
  File "datamodel_code_generator/parser/jsonschema.py", line 1527, in parse_obj
    self.parse_ref(obj, path)
  File "datamodel_code_generator/parser/jsonschema.py", line 1439, in parse_ref
    self.resolve_ref(obj.ref)
  File "datamodel_code_generator/parser/jsonschema.py", line 1423, in resolve_ref
    self._parse_file(
  File "datamodel_code_generator/parser/jsonschema.py", line 1638, in _parse_file
    self.parse_obj(obj_name, root_obj, path_parts or ["#"])
  File "datamodel_code_generator/parser/jsonschema.py", line 1518, in parse_obj
    self.parse_object(name, obj, path)
  File "datamodel_code_generator/parser/jsonschema.py", line 885, in parse_object
    fields = self.parse_object_fields(obj, path, get_module_name(class_name, None))
  File "datamodel_code_generator/parser/jsonschema.py", line 840, in parse_object_fields
    field_type = self.parse_item(modular_name, field, [*path, field_name])
  File "datamodel_code_generator/parser/jsonschema.py", line 1000, in parse_item
    return self.parse_all_of(
  File "datamodel_code_generator/parser/jsonschema.py", line 755, in parse_all_of
    return self._parse_object_common_part(
  File "datamodel_code_generator/parser/jsonschema.py", line 651, in _parse_object_common_part
    self.model_resolver.delete(path)
  File "datamodel_code_generator/reference.py", line 668, in delete
    del self.references[self.resolve_ref(path)]
KeyError: 'components/schema/components/schema/pet.yaml/kind#-datamodel-code-generator-#-allOf-#-special-#'
```

**To Reproduce**

Example schema:

`/openapi.yaml`

```yaml
openapi: 3.1.0
paths: {}
components:
  schemas:
    Animals:
      $ref: ./components/schema/animal.yaml
    Pets:
      $ref: ./components/schema/pet.yaml
servers:
  - url: /api
info:
  title: Example
  version: "1.0"
  description: Example API
tags:
  - name: Animals
    description: Information about Animals.
  - name: Pets
    description: Information about Pets.
```

`/components/schema/animal.yaml`

```yaml
title: Animal
type: object
additionalProperties: false
properties:
  kind:
    type: string
    description: The kind of the animal
    enum:
      - CAT
      - DOG
```

`/components/schema/pet.yaml`

```yaml
title: Pet
type: object
additionalProperties: false
properties:
  kind:
    description: The kind of the pet
    type: string
    allOf:
      - $ref: ./animal.yaml#/properties/kind
```

Used commandline:
```
$ datamodel-codegen --input-file-type openapi --input "openapi/openapi.yaml" --output "openapi/models.py" --target-python-version 3.9 --snake-case-field --use-field-description --capitalise-enum-members --use-default-kwarg --openapi-scopes schemas paths parameters --use-operation-id-as-name --use-title-as-name --field-include-all-keys --output-model-type pydantic_v2.BaseModel --field-constraints --disable-warnings --keep-model-order --collapse-root-models
```

**Expected behavior**

Expected output
```
# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-09-14T03:35:50+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, RootModel


class Animal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Optional[Kind] = None
    """
    The kind of the animal
    """


class Animals(RootModel):
    root: Animal


class Kind(Enum):
    CAT = 'CAT'
    DOG = 'DOG'


class Pet(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Optional[Kind] = None
    """
    The kind of the pet
    """


class Pets(RootModel):
    root: Pet
```

**Version:**
 - OS: macOS 13.5.1
 - Python version: 3.9
 - datamodel-code-generator version: 0.21.5

**Additional context**
I'll open a PR with a change that hopefully fixes this, changing [this line](https://github.com/koxudaxi/datamodel-code-generator/blob/master/datamodel_code_generator/parser/jsonschema.py#L675-L676) from:

```python
        if ignore_duplicate_model and not fields and len(base_classes) == 1:
            self.model_resolver.delete(path)
            return self.data_type(reference=base_classes[0])
```

to:

```python
        if ignore_duplicate_model and not fields and len(base_classes) == 1:
            with self.model_resolver.current_base_path_context(self.model_resolver._base_path):
                self.model_resolver.delete(path)
                return self.data_type(reference=base_classes[0])
```

**Comment by koxudaxi** [comment]
The bug was fixed in `0.22.0`.
Thank you so much!!
