### ISSUE TITLE
Example from README.md doesn't work

### ISSUE THREAD

**Issue by lsloan** [koxudaxi/datamodel-code-generator#1571]
**Describe the bug**
Example from `README.md` doesn't work.

**To Reproduce**

Example schema:
Use `api.yaml` from `README.md`.

<details>
<summary>api.yaml</summary>

```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                x-amazon-apigateway-integration:
                  uri:
                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PythonVersionFunction.Arn}/invocations
                  passthroughBehavior: when_no_templates
                  httpMethod: POST
                  type: aws_proxy
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                x-amazon-apigateway-integration:
                  uri:
                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PythonVersionFunction.Arn}/invocations
                  passthroughBehavior: when_no_templates
                  httpMethod: POST
                  type: aws_proxy
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    x-amazon-apigateway-integration:
      uri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PythonVersionFunction.Arn}/invocations
      passthroughBehavior: when_no_templates
      httpMethod: POST
      type: aws_proxy
components:
  schemas:
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    apis:
      type: array
      items:
        type: object
        properties:
          apiKey:
            type: string
            description: To be used as a dataset parameter value
          apiVersionNumber:
            type: string
            description: To be used as a version parameter value
          apiUrl:
            type: string
            format: uri
            description: "The URL describing the dataset's fields"
          apiDocumentationUrl:
            type: string
            format: uri
            description: A URL to the API console for each API
```

</details>

Used commandline:
```sh
datamodel-codegen --input api.yaml --output model.py
```

**Expected behavior**
I expected to see `model.py` created from `api.yaml` as explained in `README.md`.  That doesn't happen, though.  I get mysterious `KeyError`s.

**Version:**
 - OS: macOS 13.5
 - Python version: 3.11.4 & 3.10.12
 - datamodel-code-generator version: 0.22.0

**Additional context**
When I try the example from `README.md`, I get a long traceback with a `KeyError` from openapi.ParameterObject.  (See below.)  At first I used Python 3.11, but same happens with Python 3.10.  I used a virtualenvironment each time.

```txt
The input file type was determined to be: openapi
This can be specificied explicitly with the `--input-file-type` option.
Traceback (most recent call last):
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/datamodel_code_generator/__main__.py", line 388, in main
    generate(
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/datamodel_code_generator/__init__.py", line 317, in generate
    from datamodel_code_generator.parser.openapi import OpenAPIParser
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/datamodel_code_generator/parser/openapi.py", line 143, in <module>
    class ComponentsObject(BaseModel):
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 184, in __new__
    complete_model_class(
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 495, in complete_model_class
    schema = apply_discriminators(simplify_schema_references(schema))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 519, in simplify_schema_references
    schema = walk_core_schema(schema, count_refs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 439, in walk_core_schema
    return f(schema, _dispatch)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 515, in count_refs
    recurse(state['definitions'][ref], count_refs)
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 503, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 227, in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 503, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 362, in handle_model_fields_schema
    replaced_field['schema'] = self.walk(v['schema'], f)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 503, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 227, in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 503, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 308, in handle_dict_schema
    schema['values_schema'] = self.walk(values_schema, f)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 503, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 323, in handle_union_schema
    new_choices.append(self.walk(v, f))
                       ^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 515, in count_refs
    recurse(state['definitions'][ref], count_refs)
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 227, in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 503, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 362, in handle_model_fields_schema
    replaced_field['schema'] = self.walk(v['schema'], f)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 503, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 227, in _handle_other_schemas
    schema['schema'] = self.walk(sub_schema, f)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 503, in count_refs
    return recurse(s, count_refs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 218, in _walk
    schema = self._schema_type_to_method[schema['type']](schema, f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 308, in handle_dict_schema
    schema['values_schema'] = self.walk(values_schema, f)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 215, in walk
    return f(schema, self._walk)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsloan/Projects/caliper-jsonschema/test/.venv/lib/python3.11/site-packages/pydantic/_internal/_core_utils.py", line 515, in count_refs
    recurse(state['definitions'][ref], count_refs)
            ~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 'datamodel_code_generator.parser.openapi.ParameterObject:140464886855328'
```

**Comment by lsloan** [comment]
I hope it doesn't seem silly that I'm reporting a problem with an example from `README.md`.  It's important to me because I thought that if I couldn't get the example to work, then maybe I'd have trouble using this tool for the purposes I have in mind, too.

**Comment by koxudaxi** [comment]
@lsloan 
Thank you for creating the issue.
The error may come from pydantic.
Could you please share your pydantic version?

I have tested the example file. It works fine with 
Python: `v3.10.12`
pydantic-2.4.2 
pydantic-core-2.10.1
datamodel-codegen: `0.22.0`

**Comment by koxudaxi** [comment]
@lsloan 
I found the root cause. Pydantic version 2.4.0 has a bug. 
https://github.com/koxudaxi/datamodel-code-generator/issues/1570

Could you please try 2.4.1 or later ?
Release:
- https://github.com/pydantic/pydantic/releases/tag/v2.4.1

PR: 
-  https://github.com/pydantic/pydantic/pull/7624
Issue:
-  https://github.com/pydantic/pydantic/issues/7611

**Comment by koxudaxi** [comment]
no response
