### ISSUE TITLE
Support for OpenAPI 2.0

### ISSUE THREAD

**Issue by woodruffw** [koxudaxi/datamodel-code-generator#1590]
First of all, thanks for this tool! I found it while looking for a way to convert an OpenAPI specification into a set of Pydantic models, and it looks fantastic.

**Is your feature request related to a problem? Please describe.**

I'm attempting to use this tool to generate a set of Pydantic models from an OpenAPI *2.0* specification. Specifically, this specification:

https://github.com/sigstore/rekor/blob/v1.3.0/openapi.yaml

The codebase associated with this specification is written in Go, and unfortunately Go's dominant Swagger/OpenAPI implementation is semi-permanently tied to OpenAPI 2.0: https://github.com/go-swagger/go-swagger/issues/1122

As a result, attempting to generate models from the above specification produces errors in the code generator:

```
Traceback (most recent call last):
  File "/Users/william/devel/sigstore-rekor-types/env/lib/python3.11/site-packages/datamodel_code_generator/__main__.py", line 388, in main
    generate(
  File "/Users/william/devel/sigstore-rekor-types/env/lib/python3.11/site-packages/datamodel_code_generator/__init__.py", line 359, in generate
    input_text = json.dumps(builder.to_schema())
                            ^^^^^^^^^^^^^^^^^^^
  File "/Users/william/devel/sigstore-rekor-types/env/lib/python3.11/site-packages/genson/schema/builder.py", line 79, in to_schema
    schema.update(self._root_node.to_schema())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/william/devel/sigstore-rekor-types/env/lib/python3.11/site-packages/genson/schema/node.py", line 62, in to_schema
    generated_schema = active_strategy.to_schema()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/william/devel/sigstore-rekor-types/env/lib/python3.11/site-packages/genson/schema/strategies/object.py", line 84, in to_schema
    schema['properties'] = self._properties_to_schema(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/william/devel/sigstore-rekor-types/env/lib/python3.11/site-packages/genson/schema/strategies/object.py", line 97, in _properties_to_schema
    schema_properties[prop] = schema_node.to_schema()
                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/william/devel/sigstore-rekor-types/env/lib/python3.11/site-packages/genson/schema/node.py", line 62, in to_schema
    generated_schema = active_strategy.to_schema()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/william/devel/sigstore-rekor-types/env/lib/python3.11/site-packages/genson/schema/strategies/object.py", line 84, in to_schema
    schema['properties'] = self._properties_to_schema(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/william/devel/sigstore-rekor-types/env/lib/python3.11/site-packages/genson/schema/strategies/object.py", line 97, in _properties_to_schema
    schema_properties[prop] = schema_node.to_schema()
                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/william/devel/sigstore-rekor-types/env/lib/python3.11/site-packages/genson/schema/node.py", line 62, in to_schema
    generated_schema = active_strategy.to_schema()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/william/devel/sigstore-rekor-types/env/lib/python3.11/site-packages/genson/schema/strategies/object.py", line 84, in to_schema
    schema['properties'] = self._properties_to_schema(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/william/devel/sigstore-rekor-types/env/lib/python3.11/site-packages/genson/schema/strategies/object.py", line 97, in _properties_to_schema
    schema_properties[prop] = schema_node.to_schema()
                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/william/devel/sigstore-rekor-types/env/lib/python3.11/site-packages/genson/schema/node.py", line 62, in to_schema
    generated_schema = active_strategy.to_schema()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/william/devel/sigstore-rekor-types/env/lib/python3.11/site-packages/genson/schema/strategies/object.py", line 84, in to_schema
    schema['properties'] = self._properties_to_schema(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/william/devel/sigstore-rekor-types/env/lib/python3.11/site-packages/genson/schema/strategies/object.py", line 97, in _properties_to_schema
    schema_properties[prop] = schema_node.to_schema()
                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/william/devel/sigstore-rekor-types/env/lib/python3.11/site-packages/genson/schema/node.py", line 62, in to_schema
    generated_schema = active_strategy.to_schema()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/william/devel/sigstore-rekor-types/env/lib/python3.11/site-packages/genson/schema/strategies/object.py", line 91, in to_schema
    schema['required'] = sorted(self._required)
                         ^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'int'
```

(This specific error appears to occur because OpenAPI 2.0 allows response HTTP codes to be denoted as integers, while 3.0 requires that they be strings.)

**Describe the solution you'd like**

I'd love it if this library supported OpenAPI 2.0 definitions in addition to the current OpenAPI 3.0 support! Doing so would expand its usability with respect to specifications produced or used within other popular languages, like Go.

**Describe alternatives you've considered**

A few alternatives I've considered:

1. Upgrading the spec I'm depending on to 3.0. This is unfortunately blocked by `go-swagger`'s lack of support for 3.0.
2. Trying another code generation tool. This tool is probably the most mature in the Python + Pydantic ecosystem; others seem to be less actively maintained and also lack OpenAPI 2.0 support.

Thank you for your consideration! If this seems interesting and you're willing to support, it's something that I _may_ be able to help out with.

**Comment by koxudaxi** [comment]
Thank you for creating this issue.
OpenAPI 2.0 (Swagger) is an old standard and, unfortunately, will not be supported in the future.
Of course, we would welcome PR if we could, but it is not worth the maintenance cost,
I recommend using a tool to convert from Swagger to OpenAPI 3.x.

**Comment by woodruffw** [comment]
Just in case others run into this: I found https://converter.swagger.io/#/Converter/convertByUrl, which will turn a Swagger 2.0 (or earlier?) definition into a 3.0 one.

**Comment by ivan-toriya-precis** [comment]
> Just in case others run into this: I found https://converter.swagger.io/#/Converter/convertByUrl, which will turn a Swagger 2.0 (or earlier?) definition into a 3.0 one.

Thanks to the comments like this, I still believe in humanity.
