### ISSUE TITLE
Invalid URL min_length constraint generated 

### ISSUE THREAD

**Issue by ankushvangari** [koxudaxi/datamodel-code-generator#1662]
**Describe the bug**
When the OpenAPI json defines a string with uri format and minLength of 1, the codegen creates a pydantic AnyUrl with a `min_length` Field constraint. However, there is no `min_length` attribute for URL constraints from [docs](https://docs.pydantic.dev/2.4/api/networks/#pydantic.networks.UrlConstraints) This creates an invalid model.py causing the below error. 

**Model.py stack trace**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Downloads/model.py", line 12, in <module>
    class PetUrlItem(RootModel[AnyUrl]):
  File "/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 184, in __new__
    complete_model_class(
  File "envs/protectai/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 498, in complete_model_class
    cls.__pydantic_core_schema__ = schema = validate_core_schema(schema)
  File "/envs/protectai/lib/python3.10/site-packages/pydantic/_internal/_core_utils.py", line 580, in validate_core_schema
    return _validate_core_schema(schema)
pydantic_core._pydantic_core.SchemaError: Invalid Schema:
model.schema.url.min_length
  Extra inputs are not permitted [type=extra_forbidden, input_value=1, input_type=int]
```

**To Reproduce**

Example openapi.json schema:

```
{
  "openapi": "3.0.3",
  "info": {
    "title": "Swagger Petstore - OpenAPI 3.0",
    "description": "This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about\nSwagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!\nYou can now help us improve the API whether it's by making changes to the definition itself or to the code.\nThat way, with time, we can improve the API in general, and expose some of the new features in OAS3.\n\n_If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_\n\nSome useful links:\n- [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)\n- [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "email": "apiteam@swagger.io"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.11"
  },
  "externalDocs": {
    "description": "Find out more about Swagger",
    "url": "http://swagger.io"
  },
  "servers": [
    {
      "url": "https://petstore3.swagger.io/api/v3"
    }
  ],
  "tags": [
    {
      "name": "pet",
      "description": "Everything about your Pets",
      "externalDocs": {
        "description": "Find out more",
        "url": "http://swagger.io"
      }
    }
  ],
  "paths": {
    "/pet": {
      "post": {
        "tags": [
          "pet"
        ],
        "summary": "Add a new pet to the store",
        "description": "Add a new pet to the store",
        "operationId": "addPet",
        "requestBody": {
          "description": "Create a new pet in the store",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Pet"
              }
            },
            "application/xml": {
              "schema": {
                "$ref": "#/components/schemas/Pet"
              }
            },
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/Pet"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Pet"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Pet"
                }
              }
            }
          },
          "405": {
            "description": "Invalid input"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Pet": {
        "required": [
          "name",
          "petUrl"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "example": 10
          },
          "petUrl": {
            "anyOf": [
              {
                "type": "string",
                "minLength": 1,
                "format": "uri"
              },
              {
                "type": "null"
              }
            ],
            "title": "Pet Url"
          }
        },
        "xml": {
          "name": "pet"
        }
      }
    },
    "requestBodies": {
      "Pet": {
        "description": "Pet object that needs to be added to the store",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Pet"
            }
          },
          "application/xml": {
            "schema": {
              "$ref": "#/components/schemas/Pet"
            }
          }
        }
      }
    }
  }
}


```

Used commandline:
```
$ datamodel-codegen --input ~/Downloads/openapi.json --input-file-type openapi --use-annotated --output-model-type "pydantic_v2.BaseModel"  --output ~/Downloads/model.py
```

Generated model.py file:

```
# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2023-11-06T19:47:15+00:00

from __future__ import annotations

from typing import Annotated, Optional

from pydantic import AnyUrl, BaseModel, Field, RootModel


class PetUrlItem(RootModel[AnyUrl]):
    root: Annotated[AnyUrl, Field(min_length=1)]


class Pet(BaseModel):
    id: Annotated[Optional[int], Field(example=10)] = None
    pet_url: Annotated[
        Optional[PetUrlItem], Field(alias='petUrl', title='Pet Url')
    ] = None

```

**Expected behavior**
Expected behavior is to generate a valid model.py The model.py should either create the parameter as a string and not AnyUrl or remove the min length constraint. 

**Version:**
 - OS: Mac
 - Python version: 3.10.10
 - datamodel-code-generator version: [22]

**Comment by koxudaxi** [comment]
@ankushvangari 
The fixed version was released
Thank you very much!!
