### ISSUE TITLE
RuntimeError: Discriminator type is not found

### ISSUE THREAD

**Issue by torazem** [koxudaxi/datamodel-code-generator#1832]
**Describe the bug**
When I try to generate models from an OpenAPI schema containing discriminators, I get an error: `RuntimeError: Discriminator type is not found`.

**To Reproduce**
Get the OpenAPI spec for the [Jira REST API](https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/#version), or the reduced example below. Try to convert it into Pydantic models using `datamodel-code-generator`.

Example schema:
```json
{
    "components": {
        "schemas": {
            "CustomContextVariable": {
                "additionalProperties": false,
                "discriminator": {
                    "mapping": {
                        "issue": "#/components/schemas/IssueContextVariable",
                        "json": "#/components/schemas/JsonContextVariable",
                        "user": "#/components/schemas/UserContextVariable"
                    },
                    "propertyName": "type"
                },
                "oneOf": [
                    {
                        "$ref": "#/components/schemas/UserContextVariable"
                    },
                    {
                        "$ref": "#/components/schemas/IssueContextVariable"
                    },
                    {
                        "$ref": "#/components/schemas/JsonContextVariable"
                    }
                ],
                "properties": {
                    "type": {
                        "description": "Type of custom context variable.",
                        "type": "string"
                    }
                },
                "required": [
                    "type"
                ],
                "type": "object"
            },
            "JsonContextVariable": {
                "description": "A JSON object with custom content.",
                "properties": {
                    "type": {
                        "description": "Type of custom context variable.",
                        "type": "string"
                    },
                    "value": {
                        "description": "A JSON object containing custom content.",
                        "type": "object"
                    }
                },
                "required": [
                    "type"
                ],
                "type": "object"
            },
            "IssueContextVariable": {
                "description": "An [issue](https://developer.atlassian.com/cloud/jira/platform/jira-expressions-type-reference#issue) specified by ID or key. All the fields of the issue object are available in the Jira expression.",
                "properties": {
                    "id": {
                        "description": "The issue ID.",
                        "format": "int64",
                        "type": "integer"
                    },
                    "key": {
                        "description": "The issue key.",
                        "type": "string"
                    },
                    "type": {
                        "description": "Type of custom context variable.",
                        "type": "string"
                    }
                },
                "required": [
                    "type"
                ],
                "type": "object"
            },
            "UserContextVariable": {
                "description": "A [user](https://developer.atlassian.com/cloud/jira/platform/jira-expressions-type-reference#user) specified as an Atlassian account ID.",
                "properties": {
                    "accountId": {
                        "description": "The account ID of the user.",
                        "type": "string"
                    },
                    "type": {
                        "description": "Type of custom context variable.",
                        "type": "string"
                    }
                },
                "required": [
                    "accountId",
                    "type"
                ],
                "type": "object"
            }
        }
    },
    "info": {
        "contact": {
            "email": "ecosystem@atlassian.com"
        },
        "description": "Jira Cloud platform REST API documentation",
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "termsOfService": "http://atlassian.com/terms/",
        "title": "The Jira Cloud platform REST API",
        "version": "1001.0.0-SNAPSHOT-157e8201994ee15df4ad7fc2b41795e7c88fbc36"
    },
    "openapi": "3.0.1",
    "paths": {},
    "servers": [
        {
            "url": "https://your-domain.atlassian.net"
        }
    ],
    "tags": []
}
```

Used commandline:
```
$ datamodel-codegen --input test-openapi.json --input-file-type openapi --output models.py --output-model-type pydantic_v2.BaseModel
```

Result:
```
Traceback (most recent call last):
  ...
  File ".../python3.11/site-packages/datamodel_code_generator/parser/base.py", line 772, in __apply_discriminator_type
    raise RuntimeError(
RuntimeError: Discriminator type is not found. test-openapi.json#/components/schemas/CustomContextVariable#-datamodel-code-generator-#-oneOf-#-special-##-datamodel-code-generator-#-oneOfCommon-#-special-#/0
```

**Expected behavior**
The command should generate a file `models.py` containing pydantic models.

**Version:**
 - OS: Ubuntu
 - Python version: 3.11.4
 - datamodel-code-generator version: 0.25.3

**Additional context**
None

**Comment by rlefkowitz** [comment]
@torazem  Amazingly, I am trying to do precisely the same thing: convert the Jira openapi spec to pydantic models. Did you have any luck with the conversion? If so, did you find a workaround to make this package work or did you find an alternative? Hope you see this. Thanks!

**Comment by roman-kouzmenko** [comment]
I am getting the same error on the following minimal example:
```
---
openapi: 3.0.3
components:
  schemas:
    Cat:
      type: object
      properties:
        meows:
          type: string
    Dog:
      type: object
      properties:
        barks:
          type: string
    Pet:
      type: object
      properties:
        petType:
          type: string
      discriminator:
        propertyName: petType
        mapping:
          dog: Dog
          cat: Cat
      oneOf:
        - $ref: '#/components/schemas/Dog'
        - $ref: '#/components/schemas/Cat'
```

**Comment by torazem** [comment]
@rlefkowitz I just saw this now...
I didn't dig much further, so I have no workaround unfortunately

**Comment by billy-doyle** [comment]
Facing this issue as well but on part of the model I don't need. Is there a way to ignore broken fields?

**Comment by C-Loftus** [comment]
Not sure if this helps, but I had the same issue and then switched from pydanticv2 basemodel to msgspec.Struct and it seems to have worked.

Example below uses the openapi docs for the us army corps of engineers:

This doesn't work
```sh
datamodel-codegen --url https://cwms-data.usace.army.mil/cwms-data/swagger-docs --output-model-type pydantic_v2.BaseModel --input-file-type openapi --target-python-version 3.12 --output . 
```

```
  File "/Users/cloftus/.local/pipx/venvs/datamodel-code-generator/lib/python3.12/site-packages/datamodel_code_generator/parser/base.py", line 1372, in parse
    self.__apply_discriminator_type(models, imports)
  File "/Users/cloftus/.local/pipx/venvs/datamodel-code-generator/lib/python3.12/site-packages/datamodel_code_generator/parser/base.py", line 822, in __apply_discriminator_type
    raise RuntimeError(
RuntimeError: Discriminator type is not found. https://cwms-data.usace.army.mil/cwms-data/swagger-docs#/components/schemas/AbstractRatingMetadata#-datamodel-code-generator-#-oneOf-#-special-##-datamodel-code-generator-#-oneOfCommon-#-special-#/0

make: *** [pydanticModels] Error 1
```

but this does work (make sure you specify a directory and not a single file)

```sh	
datamodel-codegen --url https://cwms-data.usace.army.mil/cwms-data/swagger-docs --output-model-type msgspec.Struct --input-file-type openapi --target-python-version 3.12 --output . 
```

**Comment by billy-doyle** [comment]
Unfortunately not. Heres an example:

```bash
datamodel-codegen --url https://platform.uat.matchstate.api.geniussports.com/swagger/americanfootball/v2/swagger.json --input-file-type openapi --output-model-type dataclasses.dataclass --target-python-version 3.12 --output .

Traceback (most recent call last):
  File "/Users/billy/Library/Application Support/uv/tools/datamodel-code-generator/lib/python3.13/site-packages/datamodel_code_generator/__main__.py", line 455, in main
    generate(
    ~~~~~~~~^
        input_=config.url or config.input or sys.stdin.read(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<68 lines>...
        formatters=config.formatters,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/billy/Library/Application Support/uv/tools/datamodel-code-generator/lib/python3.13/site-packages/datamodel_code_generator/__init__.py", line 489, in generate
    results = parser.parse()
  File "/Users/billy/Library/Application Support/uv/tools/datamodel-code-generator/lib/python3.13/site-packages/datamodel_code_generator/parser/base.py", line 1291, in parse
    self.__apply_discriminator_type(models, imports)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/billy/Library/Application Support/uv/tools/datamodel-code-generator/lib/python3.13/site-packages/datamodel_code_generator/parser/base.py", line 781, in __apply_discriminator_type
    raise RuntimeError(msg)
RuntimeError: Discriminator type is not found. https://platform.uat.matchstate.api.geniussports.com/swagger/americanfootball/v2/swagger.json#/components/schemas/GeniusSports.Sports.AmericanFootball.Contracts.V2.EnhancedMatchState.Yard
```

```bash
datamodel-codegen --url https://platform.uat.matchstate.api.geniussports.com/swagger/americanfootball/v2/swagger.json --input-file-type openapi --output-model-type msgspec.Struct --target-python-version 3.12 --output .

Traceback (most recent call last):
  File "/Users/billy/Library/Application Support/uv/tools/datamodel-code-generator/lib/python3.13/site-packages/datamodel_code_generator/__main__.py", line 455, in main
    generate(
    ~~~~~~~~^
        input_=config.url or config.input or sys.stdin.read(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<68 lines>...
        formatters=config.formatters,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/billy/Library/Application Support/uv/tools/datamodel-code-generator/lib/python3.13/site-packages/datamodel_code_generator/__init__.py", line 489, in generate
    results = parser.parse()
  File "/Users/billy/Library/Application Support/uv/tools/datamodel-code-generator/lib/python3.13/site-packages/datamodel_code_generator/parser/base.py", line 1291, in parse
    self.__apply_discriminator_type(models, imports)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/billy/Library/Application Support/uv/tools/datamodel-code-generator/lib/python3.13/site-packages/datamodel_code_generator/parser/base.py", line 776, in __apply_discriminator_type
    check_paths(base_class.reference, mapping)  # pyright: ignore[reportArgumentType]
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/billy/Library/Application Support/uv/tools/datamodel-code-generator/lib/python3.13/site-packages/datamodel_code_generator/parser/base.py", line 759, in check_paths
    if (model.path.split("#/")[-1] != path.split("#/")[-1]) and (
        ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'path'
```
