### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_list'

### ISSUE THREAD

**Issue by comic31** [koxudaxi/datamodel-code-generator#2069]
**Describe the bug**

Fail to generate python code with an `array` of `$ref` from an `allof`, an `AttributeError` has been raised by the lib.

If this is not a bug, please let me know if I'm doing something wrong.

**To Reproduce**

Example schema:
```yaml
    PetOpts:
      type: string
    ProjectedPet:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
        opts:
          type: array
          items:
            $ref: "#/components/schemas/PetOpts"
    Pet:
      allOf:
        - $ref: "#/components/schemas/ProjectedPet"
      required:
          - id
          - name
          - opts
```

Used commandline:
```
datamodel-codegen --input api.yaml --output model.py --input-file-type openapi --use-annotated --collapse-root-models  --use-standard-collections --capitalize-enum-members  --target-python-version 3.10 --output-model-type pydantic_v2.BaseModel
```

**Actual behavior**
```
AttributeError: 'NoneType' object has no attribute 'is_list'
```

**Expected behavior**
```python
class ProjectedPet(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    tag: Optional[str] = None
    opts: Optional[list[str]] = None


class Pet(ProjectedPet):
    id: int
    name: str
    opts: list[str]
```

**Version:**
 - OS: MacOS 14.6.1
 - Python version: 3.11
 - datamodel-code-generator version: 0.25.9

**Additional context**

The traceback
```text
Traceback (most recent call last):
  File "/Users/user/work/issue-datamodel-code-generator/.venv/lib/python3.11/site-packages/datamodel_code_generator/__main__.py", line 445, in main
    generate(
  File "/Users/user/work/issue-datamodel-code-generator/.venv/lib/python3.11/site-packages/datamodel_code_generator/__init__.py", line 473, in generate
    results = parser.parse()
              ^^^^^^^^^^^^^^
  File "/Users/user/work/issue-datamodel-code-generator/.venv/lib/python3.11/site-packages/datamodel_code_generator/parser/base.py", line 1366, in parse
    self.__collapse_root_models(
  File "/Users/user/work/issue-datamodel-code-generator/.venv/lib/python3.11/site-packages/datamodel_code_generator/parser/base.py", line 1015, in __collapse_root_models
    elif data_type.parent.is_list:
         ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_list'
```

**Comment by zaphod72** [comment]
```
    Pet:
      allOf:
        - $ref: "#/components/schemas/ProjectedPet"
        - type: object
          required:
            - id
            - name
            - opts
 ```

**Comment by bkcsfi** [comment]
I'm getting the same error with version 0.26.5   and openapi spec https://docs.shipstation.com/_spec/openapi.json?download

```shell
$ datamodel-codegen --input ./api_model/openapi-v2-20250131.json --output-model-type pydantic_v2.BaseModel --snake-case-field --allow-extra-fields --use-standard-collections --use-union-operator --force-optional --allow-population-by-field-name --target-python-version=3.11 --collapse-root-models --use-schema-description --capitalise-enum-members --enable-version-header --use-annotated --output-datetime-class datetime

The input file type was determined to be: openapi
This can be specified explicitly with the `--input-file-type` option.
/home/vscode/.local/share/virtualenvs/virtualenv-S6O_fdF0/lib/python3.12/site-packages/datamodel_code_generator/parser/jsonschema.py:341: UserWarning: format of 'url' not understood for 'string' - using default
  warn(f'format of {format__!r} not understood for {type_!r} - using default')
Traceback (most recent call last):
  File "/home/vscode/.local/share/virtualenvs/virtualenv-S6O_fdF0/lib/python3.12/site-packages/datamodel_code_generator/__main__.py", line 494, in main
    generate(
  File "/home/vscode/.local/share/virtualenvs/virtualenv-S6O_fdF0/lib/python3.12/site-packages/datamodel_code_generator/__init__.py", line 507, in generate
    results = parser.parse()
              ^^^^^^^^^^^^^^
  File "/home/vscode/.local/share/virtualenvs/virtualenv-S6O_fdF0/lib/python3.12/site-packages/datamodel_code_generator/parser/base.py", line 1415, in parse
    self.__collapse_root_models(
  File "/home/vscode/.local/share/virtualenvs/virtualenv-S6O_fdF0/lib/python3.12/site-packages/datamodel_code_generator/parser/base.py", line 1064, in __collapse_root_models
    elif data_type.parent.is_list:
         ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'is_list'

```

**Comment by gaborbernat** [comment]
PR welcome.
