### ISSUE TITLE
error when generating citation-style-language/schema

### ISSUE THREAD

**Issue by elonzh** [koxudaxi/datamodel-code-generator#266]
**Describe the bug**
error when generating citation-style-language/schema

**To Reproduce**

Example schema:

https://raw.githubusercontent.com/citation-style-language/schema/v1.0.1/csl-data.json

Used commandline:
```
❯ datamodel-codegen --input ~/Documents/csl-data.json --output model.py
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/datamodel_code_generator/__main__.py", line 258, in main
    generate(
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/datamodel_code_generator/__init__.py", line 213, in generate
    results = parser.parse()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/datamodel_code_generator/parser/base.py", line 253, in parse
    self.parse_raw()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/datamodel_code_generator/parser/jsonschema.py", line 834, in parse_raw
    root_obj = JsonSchemaObject.parse_obj(self.raw_obj)
  File "pydantic/main.py", line 515, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 10 validation errors for JsonSchemaObject
items
  value is not a valid list (type=type_error.list)
items -> properties -> type -> required
  value is not a valid list (type=type_error.list)
items -> properties -> id -> required
  value is not a valid list (type=type_error.list)
items -> properties -> author -> items
  value is not a valid list (type=type_error.list)
items -> properties -> author -> items -> type
  str type expected (type=type_error.str)
items -> properties -> author -> items -> type -> 0
  str type expected (type=type_error.str)
items -> properties -> author -> items -> type -> 1
  str type expected (type=type_error.str)
items -> properties -> accessed -> type
  str type expected (type=type_error.str)
items -> properties -> accessed -> type -> 0
  str type expected (type=type_error.str)
items -> properties -> accessed -> type -> 1
  str type expected (type=type_error.str)
```

**Expected behavior**

no exceptions reported.

**Version:**
 - OS: macOS 10.15.7 (19H15)
 - Python version: 3.8.3
 - datamodel-code-generator version: 0.6.7

**Additional context**

**Comment by koxudaxi** [comment]
Thank you for creating this issue.
I have reproduced the problem. I will fix it.

**Comment by koxudaxi** [comment]
@elonzh 
I have checked the schema.
I think this schema is invalid.
1. required has boolean. I expect a string or a list of string https://json-schema.org/understanding-json-schema/reference/object.html#required-properties
2. `type: [{...}]` is not valid. I guess `items: [{...}]` is correct.
```json
            "author": {
                "type": "array",
                "items": {
                    "id": "name-variable",
                    "type": [
                        {
                            "properties": {
                                "family" : {
                                    "type": "string" 
```

```
   "description": "JSON schema (draft 3) for CSL input data"
```
Also, this schema version may be draft 3 . but, I didn't check about the version.

**Comment by elonzh** [comment]
Thanks ! I will report this issue to the CSL project.

**Comment by koxudaxi** [comment]
I agree. I add the minimum supported version in the document.
