### ISSUE TITLE
An array of enum is not working as expected

### ISSUE THREAD

**Issue by themmes** [koxudaxi/datamodel-code-generator#268]
**Describe the bug**

It produces a Enumeration with key with `None_` prepended and without quotes around the value

```
Traceback (most recent call last):
  File "/Users/tomhemmes/miniconda3/envs/py38/lib/python3.8/site-packages/datamodel_code_generator/__main__.py", line 244, in main
    generate(
  File "/Users/tomhemmes/miniconda3/envs/py38/lib/python3.8/site-packages/datamodel_code_generator/__init__.py", line 202, in generate
    results = parser.parse()
  File "/Users/tomhemmes/miniconda3/envs/py38/lib/python3.8/site-packages/datamodel_code_generator/parser/base.py", line 354, in parse
    body = format_code(body, self.target_python_version)
  File "/Users/tomhemmes/miniconda3/envs/py38/lib/python3.8/site-packages/datamodel_code_generator/format.py", line 26, in format_code
    code = apply_black(code, python_version)
  File "/Users/tomhemmes/miniconda3/envs/py38/lib/python3.8/site-packages/datamodel_code_generator/format.py", line 41, in apply_black
    return black.format_str(
  File "/Users/tomhemmes/miniconda3/envs/py38/lib/python3.8/site-packages/black.py", line 725, in format_str
    src_node = lib2to3_parse(src_contents.lstrip(), mode.target_versions)
  File "/Users/tomhemmes/miniconda3/envs/py38/lib/python3.8/site-packages/black.py", line 836, in lib2to3_parse
    raise exc from None
black.InvalidInput: Cannot parse: 10:23:     None_Item_1 = Item 1
```

**To Reproduce**

Example schema:
```json
{
  "$id": "item_types.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "item_types",
  "description": "JSON Schema for item_types",
  "type": "array",
  "items": {
    "enum": [
      "Item 1",
      "Item 2",
      "Item 3"
    ]
  }
}
```

Used commandline:
```
$ datamodel-codegen --input test.json --input-file-type jsonschema --output test.py
```

**Expected behavior**
A clear and concise description of what you expected to happen

**Version:**
 - OS: macOS Catalina 10.15.4 (19E287)
- Python version: Python 3.8
- datamodel-code-generator version: datamodel-codegen --version
0.6.2

**Additional context**

**Comment by themmes** [comment]
Absolutely my bad, the "enum" is missing a type definition!

**Comment by themmes** [comment]
Maybe I shouldn't close this, as it might be considered an issue that the library does not handle is very gracefully

**Comment by koxudaxi** [comment]
Thank you for your good suggestion.
I agree We should implement an error message.
Or, This code-generator has a feature of validation schemas.
The error message may recommend using the option.

**Comment by themmes** [comment]
@koxudaxi I see you want to receive feedback. What exactly would you like to know? My 2 cents:

1. Yes, error messages should always be actionable
2. I think by default referring to the validator is low hanging fruit!

**Comment by koxudaxi** [comment]
Thank you for your feedback.
I don't prefer to broke current behavior.
The error messages should suggest using the validation option.
I don't want to think about implementing all error patterns 😣

**Comment by ilovelinux** [comment]
@koxudaxi @gaborbernat 
We now support `enum` without `type`.
I just tested with v0.35.0 the provided example: no error is raised and code is generated.

<details><summary>Output</summary>
<pre><code>$ datamodel-codegen --input test.json --input-file-type jsonschema
# generated by datamodel-codegen:
#   filename:  test.json

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, Field


class ItemType(Enum):
    Item_1 = 'Item 1'
    Item_2 = 'Item 2'
    Item_3 = 'Item 3'


class ItemTypes(BaseModel):
    __root__: List[ItemType] = Field(
        ..., description='JSON Schema for item_types', title='item_types'
    )</code></pre>
</details> 

This issue can be closed 🙂
