### ISSUE TITLE
Ref in OpenAPI not working

### ISSUE THREAD

**Issue by shreyas44** [koxudaxi/datamodel-code-generator#500]
**Describe the bug**

**To Reproduce**

Example schema:
```yaml
# openapi.yaml

components:
  schemas:
    Foo:
      allOf:
        - $ref: "test.yaml#/Test"
```

```yaml
# test.yaml

TestNested:
  type: object
  properties:
    test_string:
      type: string
Test:
  allOf:
    - $ref: "#/TestNested"
```

Used commandline:
```
$ datamodel-codegen --input openapi.yaml --input-file-type openapi > ./models.py
```

**Expected behavior**
The `$ref` in `test.yaml/Test` resolves to `test1.yaml#/TestNested`

**Version:**
 - OS: Ubuntu 20.04.1 LTS
 - Python version: 3.8.10
 - datamodel-code-generator version: [e.g. 22]

**Additional context**

The errors logs
```log
Traceback (most recent call last):
  File "/home/ubuntu/gordian/gordian-airline-api/lib/python3.8/site-packages/datamodel_code_generator/__main__.py", line 431, in main
    generate(
  File "/home/ubuntu/gordian/gordian-airline-api/lib/python3.8/site-packages/datamodel_code_generator/__init__.py", line 346, in generate
    results = parser.parse()
  File "/home/ubuntu/gordian/gordian-airline-api/lib/python3.8/site-packages/datamodel_code_generator/parser/base.py", line 427, in parse
    _, sorted_data_models, require_update_action_models = sort_data_models(
  File "/home/ubuntu/gordian/gordian-airline-api/lib/python3.8/site-packages/datamodel_code_generator/parser/base.py", line 115, in sort_data_models
    return sort_data_models(
  File "/home/ubuntu/gordian/gordian-airline-api/lib/python3.8/site-packages/datamodel_code_generator/parser/base.py", line 115, in sort_data_models
    return sort_data_models(
  File "/home/ubuntu/gordian/gordian-airline-api/lib/python3.8/site-packages/datamodel_code_generator/parser/base.py", line 115, in sort_data_models
    return sort_data_models(
  [Previous line repeated 97 more times]
  File "/home/ubuntu/gordian/gordian-airline-api/lib/python3.8/site-packages/datamodel_code_generator/parser/base.py", line 174, in sort_data_models
    raise Exception(f'A Parser can not resolve classes: {unresolved_classes}.')
Exception: A Parser can not resolve classes: [class: test.yaml#/Test references: frozenset({'test.yaml#/TestNested'})], [class: openapi.yaml#/components/schemas/Foo references: frozenset({'test.yaml#/Test'})].
```

The below change seems to remove the errors
```diff
-   - $ref: "#/TestNested"
+   - $ref: "test.yaml#/TestNested"
```

Initially I thought this may be a problem with the ref path resolution, however from the error logs the ref path seems to be resolved correctly. And I'm not entirely sure if this problem arises from the ref being _nested_ or something else.

**Comment by koxudaxi** [comment]
@shreyas44 
Thank you for creating this issue.
The code-generator doesn't support reference which is not started with `#/components` in OpenAPI.
I will implement the feature.

Thank you!!

**Comment by shreyas44** [comment]
Ahh got it, thanks!

**Comment by haviduck** [comment]
i had a ref issue aswell, but running it through mermades converter solved it. i looked at this, and flattening sure looks promizing: https://github.com/sosed/openapi-ref-flatten

**Comment by shreyas44** [comment]
Hey @koxudaxi, I know I'm very late but thanks a lot!
