### ISSUE TITLE
 jsonschema example command from documentation errs

### ISSUE THREAD

**Issue by reubano** [koxudaxi/datamodel-code-generator#685]
**Describe the bug**
 jsonschema example command from documentation errors

**To Reproduce**
Example schema:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string",
      "description": "The person's first name."
    },
    "lastName": {
      "type": "string",
      "description": "The person's last name."
    },
    "age": {
      "description": "Age in years which must be equal to or greater than zero.",
      "type": "integer",
      "minimum": 0
    },
    "friends": {
      "type": "array"
    },
    "comment": {
      "type": "null"
    }
  }
}

```

Used commandline:
```bash
datamodel-codegen  --input person.json --input-file-type jsonschema --output model.py
```

**Expected behavior**
No error

**Version:**
 - OS: macOS 12.0.1
 - Python version: 3.9
 - datamodel-code-generator version: 0.11.15

**Additional context**
```python
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/toml/decoder.py", line 737, in load_line
    raise ValueError("Invalid date or number")
ValueError: Invalid date or number

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/reubano/Library/Python/3.9/bin/datamodel-codegen", line 8, in <module>
    sys.exit(main())
  File "/Users/reubano/Library/Python/3.9/lib/python/site-packages/datamodel_code_generator/__main__.py", line 436, in main
    for k, v in toml.load(str(pyproject_toml_path))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/toml/decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Invalid date or number (line 2 column 1 char 15)
```

**Comment by koxudaxi** [comment]
@reubano 
```python
  File "/Users/reubano/Library/Python/3.9/lib/python/site-packages/datamodel_code_generator/__main__.py", line 436, in main
    for k, v in toml.load(str(pyproject_toml_path))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/toml/decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Invalid date or number (line 2 column 1 char 15)
```
I guess the error came from your `pyproejct.toml`
Could you please share the `pyproejct.toml`?
