### ISSUE TITLE
Parsing GitHub API OpenAPI spec fails (recursion error)

### ISSUE THREAD

**Issue by alexpovel** [koxudaxi/datamodel-code-generator#781]
### Discussed in https://github.com/koxudaxi/datamodel-code-generator/discussions/778

<div type='discussions-op-text'>

<sup>Originally posted by **alexpovel** May 29, 2022</sup>
GitHub itself has an API, described using [OpenAPI](https://docs.github.com/en/rest/overview/openapi-description). The source files are in [this repository](https://github.com/github/rest-api-description).

However, running

```bash
$ datamodel-codegen --url "https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json"
```

fails, with the traceback tail being

```python-traceback
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 137, in deepcopy
    d = id(x)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

(there's hundreds of these from the recursion, so I'm omitting the full traceback).

Running `datamodel-codegen` version `0.13.0` in Python `3.9.2` on Debian 11. I also have a `poetry.lock` file if need be.

Is this an issue with the JSON file itself? Or maybe with `pydantic`? This is the head of the traceback (omitting the hundreds of recursive calls in the middle again), where `pydantic` seems to be the origin of the calls:

```python-traceback
/home/alex/.cache/pypoetry/virtualenvs/avcn-7lhM2XME-py3.9/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py:260: UserWarning: format of 'uri-template' not understood for 'string' - using default
  warn(
Traceback (most recent call last):
  File "/home/alex/.cache/pypoetry/virtualenvs/avcn-7lhM2XME-py3.9/lib/python3.9/site-packages/datamodel_code_generator/__main__.py", line 541, in main
    generate(
  File "/home/alex/.cache/pypoetry/virtualenvs/avcn-7lhM2XME-py3.9/lib/python3.9/site-packages/datamodel_code_generator/__init__.py", line 367, in generate
    results = parser.parse()
  File "/home/alex/.cache/pypoetry/virtualenvs/avcn-7lhM2XME-py3.9/lib/python3.9/site-packages/datamodel_code_generator/parser/base.py", line 449, in parse
    self.parse_raw()
  File "/home/alex/.cache/pypoetry/virtualenvs/avcn-7lhM2XME-py3.9/lib/python3.9/site-packages/datamodel_code_generator/parser/openapi.py", line 393, in parse_raw
    self.parse_raw_obj(
  File "/home/alex/.cache/pypoetry/virtualenvs/avcn-7lhM2XME-py3.9/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1149, in parse_raw_obj
    self.parse_obj(name, JsonSchemaObject.parse_obj(raw), path)
  File "/home/alex/.cache/pypoetry/virtualenvs/avcn-7lhM2XME-py3.9/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1164, in parse_obj
    self.parse_object(name, obj, path)
  File "/home/alex/.cache/pypoetry/virtualenvs/avcn-7lhM2XME-py3.9/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 599, in parse_object
    fields=self.parse_object_fields(
  File "/home/alex/.cache/pypoetry/virtualenvs/avcn-7lhM2XME-py3.9/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 545, in parse_object_fields
    field_type = self.parse_item(modular_name, field, [*path, field_name])
  File "/home/alex/.cache/pypoetry/virtualenvs/avcn-7lhM2XME-py3.9/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 645, in parse_item
    return self.parse_array_fields(
  File "/home/alex/.cache/pypoetry/virtualenvs/avcn-7lhM2XME-py3.9/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 753, in parse_array_fields
    data_types=self.parse_list_item(
  File "/home/alex/.cache/pypoetry/virtualenvs/avcn-7lhM2XME-py3.9/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 720, in parse_list_item
    return [
  File "/home/alex/.cache/pypoetry/virtualenvs/avcn-7lhM2XME-py3.9/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 721, in <listcomp>
    self.parse_item(
  File "/home/alex/.cache/pypoetry/virtualenvs/avcn-7lhM2XME-py3.9/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 639, in parse_item
    return self.get_ref_data_type(item.ref)
  File "/home/alex/.cache/pypoetry/virtualenvs/avcn-7lhM2XME-py3.9/lib/python3.9/site-packages/datamodel_code_generator/parser/jsonschema.py", line 436, in get_ref_data_type
    return self.data_type(reference=reference)
  File "/home/alex/.cache/pypoetry/virtualenvs/avcn-7lhM2XME-py3.9/lib/python3.9/site-packages/datamodel_code_generator/types.py", line 209, in __init__
    super().__init__(**values)
  File "/home/alex/.cache/pypoetry/virtualenvs/avcn-7lhM2XME-py3.9/lib/python3.9/site-packages/datamodel_code_generator/reference.py", line 45, in __init__
    super().__init__(**values)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1038, in pydantic.main.validate_model
  File "pydantic/fields.py", line 857, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1074, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1121, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 313, in pydantic.class_validators._generic_validator_basic.lambda12
  File "pydantic/main.py", line 679, in pydantic.main.BaseModel.validate
  File "pydantic/main.py", line 605, in pydantic.main.BaseModel._copy_and_set_values
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.9/copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
```

Perhaps I'm doing something wrong as well? Sorry too if this is wrong for 'discussions', I can also post it as an issue if desired. Please also let me know if the issue is not rooted in `datamodel-code-generator`, I'll pack my bags.</div>

**Comment by alexpovel** [comment]
I dug some more, using [`openapi-spec-validator`](https://github.com/p1c2u/openapi-spec-validator). It also falls over on the *referenced* API spec:

```shell
$ curl -s 'https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json' | openapi-spec-validator -
# Validation Error

Required list has not defined properties: ['content', 'encoding']
```

We can further investigate this using proper Python objects, but the resulting exception object is basically empty:

```python
from openapi_spec_validator import validate_spec_url
from openapi_spec_validator.exceptions import OpenAPIValidationError

try:
    validate_spec_url(
        "https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json"
    )
except OpenAPIValidationError as e:
    print(e._contents())
```

will print

```python

{
    "message": "Required list has not defined properties: ['encoding', 'content']",
    "cause": None,
    "context": [],
    "validator": <unset>,
    "validator_value": <unset>,
    "path": deque([]),
    "schema_path": deque([]),
    "instance": <unset>,
    "schema": <unset>,
    "parent": None,
}
```

So *somewhere* inside the huge GitHub OpenAPI v3 spec, there is a `$ref` that neither `datamodel-code-generator` nor `openapi-spec-validator` like. I have no idea how to pin this down further.

---

However, `openapi-spec-validator` approves of the *dereferenced* JSON spec:

```shell
$ curl -s 'https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/dereferenced/api.github.com.deref.json' | openapi-spec-validator -
OK
```

This makes it seems the issue is in `datamodel-code-generator` after all. Sadly I have no clue where to even begin looking (spent 2 hours in the debugger). If we launch `datamodel-codegen` at the *dereferenced* spec, it doesn't find a model at all:

```shell
$ datamodel-codegen --url "https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/dereferenced/api.github.com.deref.json"
Models not found in the input data
```

This is with:

```shell
$ datamodel-codegen --version
0.13.0
```

```shell
$ python -m pip show openapi-spec-validator
Name: openapi-spec-validator
Version: 0.3.3
```

```shell
$ cat /etc/os-*
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
```

```shell
$ python --version
Python 3.9.2
```
