### ISSUE TITLE
Support for Pydantic v2

### ISSUE THREAD

**Issue by ofek** [koxudaxi/datamodel-code-generator#803]
Just FYI https://pydantic-docs.helpmanual.io/blog/pydantic-v2/

Likely requires dropping < v2

**Comment by Kludex** [comment]
@koxudaxi Do you have bandwidth for this? Is there anything we can do to help here?

**Comment by koxudaxi** [comment]
@Kludex 
I appreciate your help :bow: 
I'm sorry. I know we should support Pydantic v2 soon :cry: 
But, Due to personal circumstances, I have yet to be able to accomplish much.
Additionally, I have been spending time addressing [this error](https://github.com/koxudaxi/pydantic-pycharm-plugin/pull/717), so the work is not progressing :(

Are you asking if the content you're talking about pertains to the output model, or is it about a library that the CLI depends on?

**Comment by koxudaxi** [comment]
@ofek @Kludex 
I have started supporting Pydantic v2.
I will merge and release the PR in a few days.

**Comment by Kludex** [comment]
Thanks 🙏

**Comment by ofek** [comment]
that's awesome thank you very much!

**Comment by koxudaxi** [comment]
@ofek  @Kludex 
I have released the new version `0.21.0`
The version can be run in Pydantic V2.
Also, There is `--output-model-type pydantic_v2.BaseModel` option to generate pydantic v2 model 

The detail is here↓
https://github.com/koxudaxi/datamodel-code-generator/releases/tag/0.21.0

## What's changes in v2 output?
### `__root__` field (a.k.a [Custom Root Types](https://docs.pydantic.dev/1.10/usage/models/#custom-root-types))
`__root__` field (a.k.a [Custom Root Types](https://docs.pydantic.dev/1.10/usage/models/#custom-root-types)) is removed in pydantic v2.
The model is changed to [RootModel](https://docs.pydantic.dev/latest/usage/models/#rootmodel-and-custom-root-types)

### pydantic.Field
https://docs.pydantic.dev/2.0/migration/#changes-to-pydanticfield

- const -> removed
- min_items (use min_length instead)
- max_items (use max_length instead)
- unique_items -> removed and the list type will be replaced by `typing.Set`. this feature is discussed in https://github.com/pydantic/pydantic-core/issues/296
- allow_mutation (use frozen instead)
- regex (use pattern instead)

### Model Config
- `pydantic.Config` -> `pydantic.ConfigDict` 
- allow_mutation —> frozen (inverse value for getting same behavior).
- allow_population_by_field_name → populate_by_name

**Comment by ofek** [comment]
```yaml
components:
  schemas:
    SharedConfig:
      properties:
        proxy:
          properties:
            http:
              type: string
            https:
              type: string
            no_proxy:
              items:
                type: string
              type: array
          type: object
        service:
          type: string
        skip_proxy:
          type: boolean
        timeout:
          type: number
      required: []
paths:
  /shared:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SharedConfig'
```

```
│ C:\Users\ofek\Desktop\code\integrations-core\datadog_checks_dev\datadog_checks\dev\tooling\confi │
│ guration\consumers\model\model_consumer.py:117 in _process_section                               │
│                                                                                                  │
│   114 │   │   │   │   field_constraints=True,                                                    │
│   115 │   │   │   )                                                                              │
│   116 │   │   │   print(f'Parsing the OpenAPI schema `{schema_name}`')                           │
│ ❱ 117 │   │   │   parsed_section = section_parser.parse()                                        │
│   118 │   │   except Exception as e:                                                             │
│   119 │   │   │   raise                                                                          │
│   120 │   │   │   print(f'Error parsing the OpenAPI schema `{schema_name}`: {e}')                │
│                                                                                                  │
│ C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\datamodel_code_generator │
│ \parser\base.py:995 in parse                                                                     │
│                                                                                                  │
│    992 │   │   format_: Optional[bool] = True,                                                   │
│    993 │   │   settings_path: Optional[Path] = None,                                             │
│    994 │   ) -> Union[str, Dict[Tuple[str, ...], Result]]:                                       │
│ ❱  995 │   │   self.parse_raw()                                                                  │
│    996 │   │                                                                                     │
│    997 │   │   if with_import:                                                                   │
│    998 │   │   │   if self.target_python_version != PythonVersion.PY_36:                         │
│                                                                                                  │
│ C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\datamodel_code_generator │
│ \parser\openapi.py:549 in parse_raw                                                              │
│                                                                                                  │
│   546 │   │   │   │   │   obj_name,                                                              │
│   547 │   │   │   │   │   raw_obj,                                                               │
│   548 │   │   │   │   ) in schemas.items():  # type: str, Dict[Any, Any]                         │
│ ❱ 549 │   │   │   │   │   self.parse_raw_obj(                                                    │
│   550 │   │   │   │   │   │   obj_name,                                                          │
│   551 │   │   │   │   │   │   raw_obj,                                                           │
│   552 │   │   │   │   │   │   [*path_parts, '#/components', 'schemas', obj_name],                │
│                                                                                                  │
│ C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\datamodel_code_generator │
│ \parser\jsonschema.py:1535 in parse_raw_obj                                                      │
│                                                                                                  │
│   1532 │   │   raw: Dict[str, Any],                                                              │
│   1533 │   │   path: List[str],                                                                  │
│   1534 │   ) -> None:                                                                            │
│ ❱ 1535 │   │   self.parse_obj(name, JsonSchemaObject.parse_obj(raw), path)                       │
│   1536 │                                                                                         │
│   1537 │   def parse_obj(                                                                        │
│   1538 │   │   self,                                                                             │
│                                                                                                  │
│ C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\datamodel_code_generator │
│ \parser\jsonschema.py:1552 in parse_obj                                                          │
│                                                                                                  │
│   1549 │   │   │   if isinstance(data_type, EmptyDataType) and obj.properties:                   │
│   1550 │   │   │   │   self.parse_object(name, obj, path)                                        │
│   1551 │   │   elif obj.properties:                                                              │
│ ❱ 1552 │   │   │   self.parse_object(name, obj, path)                                            │
│   1553 │   │   elif obj.patternProperties:                                                       │
│   1554 │   │   │   self.parse_root_type(name, obj, path)                                         │
│   1555 │   │   elif obj.type == 'object':                                                        │
│                                                                                                  │
│ C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\datamodel_code_generator │
│ \parser\jsonschema.py:909 in parse_object                                                        │
│                                                                                                  │
│    906 │   │   )                                                                                 │
│    907 │   │   class_name = reference.name                                                       │
│    908 │   │   self.set_title(class_name, obj)                                                   │
│ ❱  909 │   │   fields = self.parse_object_fields(obj, path, get_module_name(class_name, None))   │
│    910 │   │   if fields or not isinstance(obj.additionalProperties, JsonSchemaObject):          │
│    911 │   │   │   data_model_type_class = self.data_model_type                                  │
│    912 │   │   else:                                                                             │
│                                                                                                  │
│ C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\datamodel_code_generator │
│ \parser\jsonschema.py:864 in parse_object_fields                                                 │
│                                                                                                  │
│    861 │   │   │   │   )                                                                         │
│    862 │   │   │   │   continue                                                                  │
│    863 │   │   │                                                                                 │
│ ❱  864 │   │   │   field_type = self.parse_item(modular_name, field, [*path, field_name])        │
│    865 │   │   │                                                                                 │
│    866 │   │   │   if self.force_optional_for_required_fields or (                               │
│    867 │   │   │   │   self.apply_default_values_for_required_fields and field.has_default       │
│                                                                                                  │
│ C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\datamodel_code_generator │
│ \parser\jsonschema.py:1038 in parse_item                                                         │
│                                                                                                  │
│   1035 │   │   elif item.is_object or item.patternProperties:                                    │
│   1036 │   │   │   object_path = get_special_path('object', path)                                │
│   1037 │   │   │   if item.properties:                                                           │
│ ❱ 1038 │   │   │   │   return self.parse_object(                                                 │
│   1039 │   │   │   │   │   name, item, object_path, singular_name=singular_name                  │
│   1040 │   │   │   │   )                                                                         │
│   1041 │   │   │   elif item.patternProperties:                                                  │
│                                                                                                  │
│ C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\datamodel_code_generator │
│ \parser\jsonschema.py:936 in parse_object                                                        │
│                                                                                                  │
│    933 │   │   │   data_model_type_class = self.data_model_root_type                             │
│    934 │   │                                                                                     │
│    935 │   │   self.set_additional_properties(class_name, obj)                                   │
│ ❱  936 │   │   data_model_type = data_model_type_class(                                          │
│    937 │   │   │   reference=reference,                                                          │
│    938 │   │   │   fields=fields,                                                                │
│    939 │   │   │   custom_base_class=obj.custom_base_path or self.base_class,                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: 'DataModelType' object is not callable
```

**Comment by koxudaxi** [comment]
@ofek 
I have tested your example.
It works fine.
I used python v3.11.4 and Linux(ubuntu)
Could you share your CLI arguments?
```bash
❯ datamodel-codegen --input openapi.yaml --input-file-type openapi
# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-07-03T22:58:36+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Proxy(BaseModel):
    http: Optional[str] = None
    https: Optional[str] = None
    no_proxy: Optional[List[str]] = None


class SharedConfig(BaseModel):
    proxy: Optional[Proxy] = None
    service: Optional[str] = None
    skip_proxy: Optional[bool] = None
    timeout: Optional[float] = None
```

**Comment by koxudaxi** [comment]
OK, I see you uses codegen as library.

**Comment by ofek** [comment]
```python
from datamodel_code_generator import DataModelType
from datamodel_code_generator.parser.openapi import OpenAPIParser

SPEC = """\
components:
  schemas:
    SharedConfig:
      properties:
        proxy:
          properties:
            http:
              type: string
            https:
              type: string
            no_proxy:
              items:
                type: string
              type: array
          type: object
        service:
          type: string
        skip_proxy:
          type: boolean
        timeout:
          type: number
      required: []
paths:
  /shared:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SharedConfig'
"""


def main():
    parser = OpenAPIParser(SPEC, data_model_type=DataModelType.PydanticV2BaseModel)
    parser.parse()


if __name__ == '__main__':
    main()
```

```
❯ C:\Users\ofek\AppData\Local\Programs\Python\Python311\python.exe ..\..\..\pd.py
C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\pydantic\main.py:292: UserWarning: Pydantic serializer warnings:
  Expected `Union[list[definition-ref], definition-ref, bool]` but got `JsonSchemaObject` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
Traceback (most recent call last):
  File "C:\Users\ofek\Desktop\pd.py", line 45, in <module>
    main()
  File "C:\Users\ofek\Desktop\pd.py", line 41, in main
    parser.parse()
  File "C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\datamodel_code_generator\parser\base.py", line 995, in parse
    self.parse_raw()
  File "C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\datamodel_code_generator\parser\openapi.py", line 549, in parse_raw
    self.parse_raw_obj(
  File "C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\datamodel_code_generator\parser\jsonschema.py", line 1535, in parse_raw_obj
    self.parse_obj(name, JsonSchemaObject.parse_obj(raw), path)
  File "C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\datamodel_code_generator\parser\jsonschema.py", line 1552, in parse_obj
    self.parse_object(name, obj, path)
  File "C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\datamodel_code_generator\parser\jsonschema.py", line 909, in parse_object
    fields = self.parse_object_fields(obj, path, get_module_name(class_name, None))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\datamodel_code_generator\parser\jsonschema.py", line 864, in parse_object_fields
    field_type = self.parse_item(modular_name, field, [*path, field_name])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\datamodel_code_generator\parser\jsonschema.py", line 1038, in parse_item
    return self.parse_object(
           ^^^^^^^^^^^^^^^^^^
  File "C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\datamodel_code_generator\parser\jsonschema.py", line 936, in parse_object
    data_model_type = data_model_type_class(
                      ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'DataModelType' object is not callable
```

**Comment by koxudaxi** [comment]
@ofek 
Thank you for your example code.
The parser needs five parameters for v2 output model type.

I will update the documents
```python
...
def main():
    from datamodel_code_generator import DataModelType, PythonVersion
    from datamodel_code_generator.model import get_data_model_types
    data_model_types = get_data_model_types(DataModelType.PydanticV2BaseModel,
                                            target_python_version=PythonVersion.PY_38)
    parser = OpenAPIParser(SPEC,
                           data_model_type=data_model_types.data_model,
                           data_model_root_type=data_model_types.root_model,
                           data_model_field_type=data_model_types.field_model,
                           data_type_manager_type=data_model_types.data_type_manager,
                           dump_resolve_reference_action=data_model_types.dump_resolve_reference_action,
                           )
    parser.parse()
 ...
 ```

**Comment by ofek** [comment]
Thanks! Finally, do you know what this warning is and how it might be resolved?

```
❯ C:\Users\ofek\AppData\Local\Programs\Python\Python311\python.exe ..\..\..\pd.py
C:\USERS\OFEK\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\Lib\site-packages\pydantic\main.py:292: UserWarning: Pydantic serializer warnings:
  Expected `Union[list[definition-ref], definition-ref, bool]` but got `JsonSchemaObject` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
```

**Comment by koxudaxi** [comment]
@ofek 
I'm checking the warning.
I don't think critical issue because unittests work fine, same as v1.
I'll reach out to you after I fix the warning.

**Comment by Kludex** [comment]
If any help is needed, feel free to ping me. 👍

**Comment by ofek** [comment]
For optional fields calling this as a library does not append a ` = None` which is now required in v2 https://docs.pydantic.dev/2.0/migration/#required-optional-and-nullable-fields

**Comment by koxudaxi** [comment]
@ofek 
I'm sorry I couldn't catch some cases.
I have released the fixed version `0.21.1`.
If the version doesn't work with your input, please share your input schema.

**Comment by koxudaxi** [comment]
@AIGeneratedUsername 
I reported the error to pydantic team.
https://github.com/pydantic/pydantic/issues/6422
They said it is not easy to fix the warning.
I should disable the warning in the datamodel-code-generator.

**Comment by esciara** [comment]
Hi. Not sure whether I should open a new issue or use this one. Since this one is still open I thought I should use it. Tell me if otherwise.

There is a problem with the generation of RootModel.

I created a brand new project and installed only `datamodel-code-generator`. Here are the dependencies I obtained:
```
annotated-types==0.6.0
argcomplete==3.2.1
black==23.12.1
click==8.1.7
datamodel-code-generator==0.25.2
dnspython==2.4.2
email-validator==2.1.0.post1
genson==1.2.2
idna==3.6
inflect==5.6.2
isort==5.13.2
Jinja2==3.1.2
MarkupSafe==2.1.3
mypy-extensions==1.0.0
packaging==23.2
pathspec==0.12.1
platformdirs==4.1.0
pydantic==2.5.3
pydantic_core==2.14.6
PyYAML==6.0.1
typing_extensions==4.9.0
```

Then I created this simple json schema file:

```json
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "conf_name": {
        "type": "string"
      }
    },
    "required": [
      "config_name"
    ]
  }
}
```

When I ran `datamodel-codegen` on it, I obtained the following result:

```python
# generated by datamodel-codegen:
#   filename:  scratch_83.json
#   timestamp: 2023-12-27T09:18:22+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class ModelItem(BaseModel):
    conf_name: Optional[str] = None


class Model(BaseModel):
    __root__: List[ModelItem]
```

Using that code results in the following error:

```
TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'
```

Digging into [Pydantic's doc on the usage of RootModel](https://docs.pydantic.dev/latest/concepts/models/#rootmodel-and-custom-root-types), I found that Pydantic v2 requires one of the following:

```python
class Model(RootModel):
    root: List[ModelItem]

# or

Model = RootModel[List[ModelItem]]
```

**Comment by koxudaxi** [comment]
@esciara 
 ` --output-model-type pydantic_v2.BaseModel`

you should use the option to generate pydantic v2 models.
```
  --output-model-type {pydantic.BaseModel,pydantic_v2.BaseModel,dataclasses.dataclass,typing.TypedDict,msgspec.Struct}
```

**Comment by esciara** [comment]
Thanks for the tip @koxudaxi!

Should that not be the default by now? Or at least, should there not be a message during generation mentioning that one or the other version is used? Otherwise it would be difficult to know...
